### ISSUE TITLE
Error cant read tile map

### ISSUE THREAD

**Issue by LunarArtemis** [ZeroDoctor/yt-java-game#6]
I use my own tilemap and got the error

Loading: map/All tiles.png...
Error loading sprite: map/All tiles.png
ERROR - TILEMANAGER: can not read tilemap:
java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "this.SPRITESHEET" is null

**Comment by ZeroDoctor** [comment]
So it looks like it can't find "map/All tiles.png", and the start of the error comes from [here](https://github.com/ZeroDoctor/yt-java-game/blob/a034529d7852d3dbf41ba2b3a9ccda4d6debb40e/game-decay/src/main/java/com/zerulus/game/graphics/SpriteSheet.java#L85). This is a common issue. So it could be that java doesn't know wheres your resource folder. This is important because `getClass().getClassLoader().getResourceAsStream(file)` requires the projects resource folder to be like

- if maven
   root/src/main/resources
- if eclipse
   [stack overflow answer](https://stackoverflow.com/questions/27934796/how-do-i-add-a-resources-folder-to-my-java-project-in-eclipse)
- if intellij
   [crunchify.com answer](https://crunchify.com/how-to-add-resources-folder-properties-at-runtime-into-intellijs-classpath-adding-property-files-to-classpath/)

it could be something else like maybe the space in "All tiles.png" but the issue and solution above is the usual culprit
